name: NaturezBoi
favicon: null
layout_spectrum: 1
typography_spectrum: 0.60316
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A0B8D0'
    - '#205880'
    - '#6888B0'
    - '#4078C8'
    - '#98B8D8'
  brandStrength: 0.660473
  lightness: 0.755067
  saturation: 0.733108
  rhythmicContrast: 0.5
purpose:
  - name: null
    item: null
    url: null
