analytics: {}
color:
  brandColors:
    - '#000000'
    - '#684810'
    - '#000000'
    - '#F8C848'
    - '#000000'
  brandStrength: 0.552364
  lightness: 0.755067
  rhythmicContrast: 0.829391
  saturation: 0.462837
cta: {}
layout_spectrum: 1
name: Immortal Body
opengraph: {}
purpose: {}
typography_spectrum: 0.3646510986565742
